import {
    sqliteTable,
    text,
    integer
} from 'drizzle-orm/sqlite-core'

export const recipes = sqliteTable("recipes", {
  id: text("id").primaryKey(),
  recipeName: text("recipe_name").notNull(),
  category: text("category").notNull(),
  area: text("area").notNull(),
  instructions: text("instructions").notNull(),
  recipeThumbnail: text("recipeThumbnail").notNull(),
  ingredient1: text("ingredient_1").notNull(),
  ingredient2: text("ingredient_2").notNull(),
  ingredient3: text("ingredient_3").notNull(),
  ingredient4: text("ingredient_4").notNull(),
  ingredient5: text("ingredient_5").notNull(),
  ingredient6: text("ingredient_6").notNull(),
  ingredient7: text("ingredient_7").notNull(),
  ingredient8: text("ingredient_8").notNull(),
  ingredient9: text("ingredient_9").notNull(),
  ingredient10: text("ingredient_10").notNull(),
  ingredient11: text("ingredient_11").notNull(),
  ingredient12: text("ingredient_12").notNull(),
  ingredient13: text("ingredient_13").notNull(),
  ingredient14: text("ingredient_14").notNull(),
  ingredient15: text("ingredient_15").notNull(),
  ingredient16: text("ingredient_16").notNull(),
  ingredient17: text("ingredient_17").notNull(),
  ingredient18: text("ingredient_18").notNull(),
  ingredient19: text("ingredient_19").notNull(),
  ingredient20: text("ingredient_20").notNull(),
  measure1: text("measure_1").notNull(),
  measure2: text("measure_2").notNull(),
  measure3: text("measure_3").notNull(),
  measure4: text("measure_4").notNull(),
  measure5: text("measure_5").notNull(),
  measure6: text("measure_6").notNull(),
  measure7: text("measure_7").notNull(),
  measure8: text("measure_8").notNull(),
  measure9: text("measure_9").notNull(),
  measure10: text("measure_10").notNull(),
  measure11: text("measure_11").notNull(),
  measure12: text("measure_12").notNull(),
  measure13: text("measure_13").notNull(),
  measure14: text("measure_14").notNull(),
  measure15: text("measure_15").notNull(),
  measure16: text("measure_16").notNull(),
  measure17: text("measure_17").notNull(),
  measure18: text("measure_18").notNull(),
  measure19: text("measure_19").notNull(),
  measure20: text("measure_20").notNull(),
  embedding: text("embedding", {
    mode: "json",
  }).notNull(),
  createdAt: integer("created_at", {
    mode: "timestamp",
  }).notNull(),
  updatedAt: integer("updated_at", {
    mode: "timestamp",
  }).notNull(),
});